#!/usr/bin/env bash
# =============================================================================
#  Clawspan — One-Command Setup
#  Run:  bash setup.sh
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

CLAWSPAN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

banner() {
  echo ""
  echo -e "${CYAN}${BOLD}"
  echo "  ██████╗██╗      █████╗ ██╗    ██╗███████╗██████╗  █████╗ ███╗   ██╗"
  echo " ██╔════╝██║     ██╔══██╗██║    ██║██╔════╝██╔══██╗██╔══██╗████╗  ██║"
  echo " ██║     ██║     ███████║██║ █╗ ██║███████╗██████╔╝███████║██╔██╗ ██║"
  echo " ██║     ██║     ██╔══██║██║███╗██║╚════██║██╔═══╝ ██╔══██║██║╚██╗██║"
  echo " ╚██████╗███████╗██║  ██║╚███╔███╔╝███████║██║     ██║  ██║██║ ╚████║"
  echo "  ╚═════╝╚══════╝╚═╝  ╚═╝ ╚══╝╚══╝ ╚══════╝╚═╝     ╚═╝  ╚═╝╚═╝  ╚═══╝"
  echo -e "${RESET}"
  echo -e "${BOLD}  Your Iron Man AI Assistant — Setup Wizard${RESET}"
  echo ""
}

step() { echo -e "\n${BLUE}${BOLD}[$1]${RESET} $2"; }
ok()   { echo -e "  ${GREEN}✓${RESET} $1"; }
warn() { echo -e "  ${YELLOW}⚠${RESET}  $1"; }
fail() { echo -e "  ${RED}✗${RESET} $1"; }
ask()  { echo -e "  ${CYAN}?${RESET}  $1"; }

# ── 1. System requirements ───────────────────────────────────────────────────

banner

step "1/7" "Checking system requirements"

check_cmd() {
  if command -v "$1" &>/dev/null; then
    ok "$1 found ($(command -v "$1"))"
  else
    fail "$1 not found"
    echo "      Install: $2"
    MISSING_DEPS=1
  fi
}

MISSING_DEPS=0
check_cmd python3   "brew install python3   OR  sudo apt install python3"
check_cmd pip3      "pip3 comes with python3"
check_cmd node      "brew install node   OR  sudo apt install nodejs"
check_cmd npm       "npm comes with node"
check_cmd git       "brew install git   OR  sudo apt install git"

if [[ "$MISSING_DEPS" == "1" ]]; then
  echo ""
  fail "Install missing dependencies above, then re-run setup.sh"
  exit 1
fi

# ── 2. Python virtual environment ────────────────────────────────────────────

step "2/7" "Setting up Python virtual environment"

if [[ ! -d "$CLAWSPAN_DIR/venv" ]]; then
  python3 -m venv "$CLAWSPAN_DIR/venv"
  ok "Created venv"
else
  ok "venv already exists"
fi

# shellcheck disable=SC1091
source "$CLAWSPAN_DIR/venv/bin/activate"

pip install --quiet --upgrade pip

if [[ -f "$CLAWSPAN_DIR/requirements.txt" ]]; then
  echo "  Installing Python dependencies..."
  pip install --quiet -r "$CLAWSPAN_DIR/requirements.txt"
  ok "Python dependencies installed"
else
  warn "requirements.txt not found — skipping pip install"
fi

# ── 3. Node dependencies (HUD) ───────────────────────────────────────────────

step "3/7" "Setting up HUD (Electron overlay)"

HUD_DIR="$CLAWSPAN_DIR/hud"
if [[ -d "$HUD_DIR" ]]; then
  cd "$HUD_DIR"
  npm install --silent
  ok "HUD dependencies installed"
  cd "$CLAWSPAN_DIR"
else
  warn "hud/ directory not found — skipping"
fi

# ── 4. API Keys wizard ───────────────────────────────────────────────────────

step "4/7" "Configuring API keys"

ENV_FILE="$CLAWSPAN_DIR/.env"
ENV_EXAMPLE="$CLAWSPAN_DIR/.env.example"

if [[ -f "$ENV_FILE" ]]; then
  echo ""
  ask "A .env file already exists. Overwrite it? (y/N)"
  read -r OVERWRITE
  if [[ "$OVERWRITE" != "y" && "$OVERWRITE" != "Y" ]]; then
    ok "Keeping existing .env — skipping key setup"
    SKIP_KEYS=1
  else
    cp "$ENV_FILE" "${ENV_FILE}.backup"
    ok "Backed up existing .env → .env.backup"
    SKIP_KEYS=0
  fi
else
  SKIP_KEYS=0
fi

if [[ "$SKIP_KEYS" == "0" ]]; then
  echo ""
  echo -e "  ${BOLD}Enter your API keys below.${RESET}"
  echo -e "  ${YELLOW}Press ENTER to skip optional keys (you can add them later in .env)${RESET}"
  echo ""

  prompt_key() {
    local label="$1"
    local var="$2"
    local required="$3"
    local hint="${4:-}"
    if [[ "$required" == "required" ]]; then
      echo -e "  ${RED}*${RESET} ${BOLD}${label}${RESET}${hint:+ — $hint}"
    else
      echo -e "  ${YELLOW}○${RESET} ${label} (optional)${hint:+ — $hint}"
    fi
    read -rp "    → " val
    echo "$var=$val"
  }

  {
    echo "# Clawspan — auto-generated by setup.sh"
    echo "# Generated: $(date)"
    echo ""
    echo "# ── LLM providers ─────────────────────────────────────────────"

    prompt_key "DeepSeek API Key" "DEEPSEEK_API_KEY" "required" \
      "platform.deepseek.com → API Keys"
    echo "DEEPSEEK_BASE_URL=https://api.deepseek.com"
    echo "DEEPSEEK_MODEL=deepseek-chat"
    echo ""

    prompt_key "OpenAI API Key" "OPENAI_API_KEY" "required" \
      "platform.openai.com → API Keys (used for embeddings)"
    echo ""

    prompt_key "Anthropic API Key" "ANTHROPIC_API_KEY" "optional" \
      "console.anthropic.com → API Keys"
    echo ""

    echo "# ── Voice stack ───────────────────────────────────────────────"
    prompt_key "Deepgram API Key" "DEEPGRAM_API_KEY" "required" \
      "console.deepgram.com → Create API Key"
    echo ""

    prompt_key "Cartesia API Key" "CARTESIA_API_KEY" "required" \
      "play.cartesia.ai → API Keys"
    prompt_key "Cartesia Voice ID" "CARTESIA_VOICE_ID" "optional" \
      "leave blank to use default British voice"
    echo ""

    echo "# ── External tools ────────────────────────────────────────────"
    prompt_key "Tavily API Key" "TAVILY_API_KEY" "optional" \
      "app.tavily.com → API Keys (web research)"
    echo ""

    prompt_key "GitHub Personal Access Token" "GITHUB_TOKEN" "optional" \
      "github.com/settings/tokens → repo + read:user scopes"
    echo ""

    echo "# ── Google OAuth (Gmail + Calendar) ───────────────────────────"
    prompt_key "Google Client ID" "GOOGLE_CLIENT_ID" "optional" \
      "console.cloud.google.com → Credentials"
    prompt_key "Google Client Secret" "GOOGLE_CLIENT_SECRET" "optional" \
      "same page as Client ID"
    echo ""

    echo "# ── AWS (infrastructure monitoring) ───────────────────────────"
    prompt_key "AWS Access Key ID" "AWS_ACCESS_KEY_ID" "optional" \
      "IAM → Users → Security credentials"
    prompt_key "AWS Secret Access Key" "AWS_SECRET_ACCESS_KEY" "optional"
    echo "AWS_DEFAULT_REGION=ap-south-1"
    echo ""

  } > "$ENV_FILE"

  ok ".env written"
fi

# ── 5. Directories & memory ──────────────────────────────────────────────────

step "5/7" "Creating data directories"

mkdir -p "$HOME/Clawspan_Docs/reports"
mkdir -p "$HOME/Clawspan_Docs/meetings"
mkdir -p "$HOME/Clawspan_Docs/technical"
mkdir -p "$HOME/Clawspan_Docs/proposals"
mkdir -p "$HOME/Clawspan_Docs/briefs"
mkdir -p "$HOME/.mempalace/palace"
mkdir -p "$HOME/.mempalace/knowledge_graph"
ok "~/Clawspan_Docs/ created"
ok "~/.mempalace/ created"

# ── 6. Install clawspan CLI ──────────────────────────────────────────────────

step "6/7" "Installing clawspan CLI"

CLI_TARGET="/usr/local/bin/clawspan"

cat > /tmp/clawspan_cli << CLISCRIPT
#!/usr/bin/env bash
# Clawspan CLI — wrapper installed by setup.sh
CLAWSPAN_DIR="${CLAWSPAN_DIR}"
VENV_PYTHON="${CLAWSPAN_DIR}/venv/bin/python"
cd "\$CLAWSPAN_DIR"

case "\${1:-}" in
  start)
    echo "[Clawspan] Starting voice mode..."
    "\$VENV_PYTHON" main.py
    ;;
  text)
    echo "[Clawspan] Starting text mode..."
    "\$VENV_PYTHON" main.py --text
    ;;
  hud)
    echo "[Clawspan] Starting HUD..."
    cd "\$CLAWSPAN_DIR/hud" && npm start &
    ;;
  stop)
    echo "[Clawspan] Stopping all processes..."
    pkill -f "main.py" 2>/dev/null && echo "  ✓ Voice process stopped" || echo "  ○ No voice process running"
    pkill -f "electron" 2>/dev/null && echo "  ✓ HUD stopped" || echo "  ○ No HUD running"
    ;;
  status)
    echo "[Clawspan] Process status:"
    pgrep -f "main.py"    &>/dev/null && echo "  ✓ Voice pipeline  RUNNING" || echo "  ○ Voice pipeline  stopped"
    pgrep -f "electron"   &>/dev/null && echo "  ✓ HUD             RUNNING" || echo "  ○ HUD             stopped"
    ;;
  logs)
    LOG_FILE="\$CLAWSPAN_DIR/clawspan.log"
    if [[ -f "\$LOG_FILE" ]]; then
      tail -f "\$LOG_FILE"
    else
      echo "  No log file found. Run: clawspan start 2>&1 | tee clawspan.log"
    fi
    ;;
  setup)
    bash "\$CLAWSPAN_DIR/setup.sh"
    ;;
  keys)
    "\${EDITOR:-nano}" "\$CLAWSPAN_DIR/.env"
    ;;
  update)
    echo "[Clawspan] Pulling latest..."
    cd "\$CLAWSPAN_DIR" && git pull
    source "\$CLAWSPAN_DIR/venv/bin/activate"
    pip install --quiet -r requirements.txt
    echo "  ✓ Updated"
    ;;
  *)
    echo ""
    echo "  Clawspan — Your Iron Man AI Assistant"
    echo ""
    echo "  Usage:  clawspan <command>"
    echo ""
    echo "  Commands:"
    echo "    start     Start in voice mode"
    echo "    text      Start in text mode (terminal chat)"
    echo "    hud       Launch the HUD overlay (Electron)"
    echo "    stop      Stop all running processes"
    echo "    status    Show which processes are running"
    echo "    logs      Tail the live log output"
    echo "    keys      Edit your .env API keys"
    echo "    update    Pull latest code + update dependencies"
    echo "    setup     Re-run the full setup wizard"
    echo ""
    ;;
esac
CLISCRIPT

if install -m 755 /tmp/clawspan_cli "$CLI_TARGET" 2>/dev/null; then
  ok "clawspan CLI installed → $CLI_TARGET"
else
  # Try with sudo
  if sudo install -m 755 /tmp/clawspan_cli "$CLI_TARGET" 2>/dev/null; then
    ok "clawspan CLI installed → $CLI_TARGET (used sudo)"
  else
    # Fallback: install to ~/.local/bin
    mkdir -p "$HOME/.local/bin"
    install -m 755 /tmp/clawspan_cli "$HOME/.local/bin/clawspan"
    ok "clawspan CLI installed → ~/.local/bin/clawspan"
    warn "Add ~/.local/bin to your PATH:  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.zshrc"
  fi
fi

# ── 7. Done ──────────────────────────────────────────────────────────────────

step "7/7" "Setup complete"

echo ""
echo -e "${GREEN}${BOLD}  ✓ Clawspan is ready.${RESET}"
echo ""
echo -e "  ${BOLD}Quick start:${RESET}"
echo "    clawspan start      — voice mode"
echo "    clawspan text       — text mode"
echo "    clawspan hud        — launch HUD"
echo "    clawspan keys       — edit API keys"
echo ""
echo -e "  ${YELLOW}Tip:${RESET} First run will prompt you to set your passphrase and complete onboarding."
echo ""
